baseURL = "http://rorasuketo.win/"
languageCode = "en-us"
title = "ro-ra-su-ke-to OST"
theme = "hugo-split-theme"

disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "rorasuketo ost"
  description = ""
  shareImage = "images/social.jpg"
  twitterHandle = ""

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "&copy;2018 Codana.me"

  # Section - Content
  [params.content]
    name = "Rorasuketo OST"
    tagline = "Chiptune. Derby."
    bio = "Rorasuketo is a ghost sports adventure made by Candice Norcross. This is the chiptune soundtrack by Michael Chadwick."

    [params.content.audio]
      enable = true
      autoplay = false
      mute = false
      #file = "/sounds/apartment.mp3"
      playlist = true
      #soundcloudId = "258744494"
      #bandcampId = "156001537"
      #bandcampUrl = "http://nebyoolae.bandcamp.com/album/close-to-the-metal"
      #bandcampUrlTitle = "Close to the Metal by Nebyoolae"

      [params.content.audio.tracks]
        [params.content.audio.tracks.track1]
          active = true
          url = "/sounds/apartment.mp3"
          name = "apartment"

        [params.content.audio.tracks.track2]
          url = "/sounds/derby-dj-1.mp3"
          name = "derby-dj-1"

        [params.content.audio.tracks.track3]
          url = "/sounds/derby-dj-2.mp3"
          name = "derby-dj-2"

        [params.content.audio.tracks.track4]
          url = "/sounds/hospital-plot.mp3"
          name = "hospital-plot"

        [params.content.audio.tracks.track5]
          url = "/sounds/hospital-quiet.mp3"
          name = "hospital-quiet"

        [params.content.audio.tracks.track6]
          url = "/sounds/lost.mp3"
          name = "lost"

        [params.content.audio.tracks.track7]
          url = "/sounds/main_street_usa.mp3"
          name = "main-street-usa"

        [params.content.audio.tracks.track8]
          url = "/sounds/respite.mp3"
          name = "respite"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/rorasuketo-screen.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/test.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1

  [[params.links]]
    [params.links.list1]
      heading = "Game"

      [[params.links.list1.link]]
        text = "Game Home"
        url = "#"

      [[params.links.list1.link]]
        text = "Ghost Sports"
        url = "#"

      [[params.links.list1.link]]
        text = "Derby"
        url = "https://en.wikipedia.org/wiki/Roller_derby"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Composer"

      [[params.links.list2.link]]
        text = "MC.Info"
        url = "http://michaelchadwick.info"

      [[params.links.list2.link]]
        text = "Soundcloud"
        url = "https://soundcloud.com/nebyoolae"

      [[params.links.list2.link]]
        text = "Bandcamp"
        url = "http://nebyoolae.bandcamp.com"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Social"

      [[params.links.list3.link]]
        text = "Candice Norcross"
        url = "https://www.facebook.com/candice.norcross"

      [[params.links.list3.link]]
        text = "Michael Chadwick"
        url = "https://www.facebook.com/michael.chadwick"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
