baseURL = ""
languageCode = "en-us"
title = "Rorasuketo OST"
theme = "hugo-split-theme"

disableKinds = ["page", "section", "taxonomy", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "Rorasuketo OST"
  description = "ghost sports adventure soundtrack"
  shareImage = "images/social.png"
  twitterHandle = ""

  # Favicon
  # favicon = "favicon.png"

  # Section - Visual
  [params.visual]

    # Video
    [params.visual.video]
      enable = true
      mute = true
      file = "video/rora-540p-low.mp4"
      # youtubeId = "dk9uNWPP7EA"

    # Image
    [params.visual.image]
      enable = true
      file = "images/rorasuketo-screen.png"
      position = "center 50%"

  # Section - Content
  [params.content]
    name = "Rorasuketo OST"
    tagline = "Chiptune. Derby."
    tagchars = "チップチューン. ダービー."
    bio = "Rorasuketo is a ghost sports adventure created and designed by Cam Norcross, and co-written by Tiffany VanPeenen. Inspired by and orchestrated with classic SNES sounds, the soundtrack was written by Michael Chadwick."

    [params.content.audio]
      enable = true
      autoplay = false
      mute = false
      playlist = true
      #file = "/sounds/main-tema.mp3"
      #soundcloudId = "258744494"
      #bandcampId = "156001537"
      #bandcampUrl = "http://nebyoolae.bandcamp.com/album/rorasuketo-ost"
      #bandcampUrlTitle = "Rorasuketo OST by Nebyoolae"

      [params.content.audio.tracks]
        [params.content.audio.tracks.track01]
          tracknum = 1
          name = "mein-tema"
          trans = "main theme"
          chars = "メインテ ー マ"
          active = true

        [params.content.audio.tracks.track02]
          tracknum = 2
          name = "apato-ochitsuita"
          trans = "apartment - calm"
          chars = "アパート - 落ち着いた"

        [params.content.audio.tracks.track03]
          tracknum = 3
          name = "apato-isogashi"
          trans = "apartment - busy"
          chars = "アパート - 忙しい"

        [params.content.audio.tracks.track04]
          tracknum = 4
          name = "kyuushi"
          trans = "rest"
          chars = "休止"

        [params.content.audio.tracks.track05]
          tracknum = 5
          name = "meinsutoritoamerika"
          trans = "main street usa"
          chars = "メインストリートアメリカ"

        [params.content.audio.tracks.track06]
          tracknum = 6
          name = "roradabi1"
          trans = "roller derby 1"
          chars = "ローラーダービー 1"

        [params.content.audio.tracks.track07]
          tracknum = 7
          name = "lala-tema"
          trans = "lala - theme"
          chars = "ララテ ー マ"

        [params.content.audio.tracks.track08]
          tracknum = 8
          name = "inbo"
          trans = "intrigue"
          chars = "陰謀"

        [params.content.audio.tracks.track09]
          tracknum = 9
          name = "ranburubatoru"
          trans = "rumble battle"
          chars = "ランブルバトル"

        [params.content.audio.tracks.track10]
          tracknum = 10
          name = "seishinbyouin-monogatari"
          trans = "clinic - story/plot"
          chars = "精神病院 - 物語"

        [params.content.audio.tracks.track11]
          tracknum = 11
          name = "roradabi2"
          trans = "roller derby 2"
          chars = "ローラーダービー 2"

        [params.content.audio.tracks.track12]
          tracknum = 12
          name = "mayou"
          trans = "lost"
          chars = "迷う"

        [params.content.audio.tracks.track13]
          tracknum = 13
          name = "meinsutoritonyuyoku"
          trans = "main street new york"
          chars = "メインストリートニューヨーク"

        [params.content.audio.tracks.track14]
          tracknum = 14
          name = "shian"
          trans = "ponder"
          chars = "思案"

        [params.content.audio.tracks.track15]
          tracknum = 15
          name = "utagai"
          trans = "suspicion"
          chars = "疑い"

        [params.content.audio.tracks.track16]
          tracknum = 16
          name = "suketo-shimai"
          trans = "skate sisters"
          chars = "スケート姉妹"

        [params.content.audio.tracks.track17]
          tracknum = 17
          name = "roradabi3"
          trans = "roller derby 3"
          chars = "ローラーダービー 3"

        [params.content.audio.tracks.track18]
          tracknum = 18
          name = "seishinbyouin-shizuka"
          trans = "clinic - quiet"
          chars = "精神病院 - 静か"

        [params.content.audio.tracks.track19]
          tracknum = 19
          name = "roradabi4"
          trans = "roller derby 4"
          chars = "ローラーダービー 4"

        [params.content.audio.tracks.track20]
          tracknum = 20
          name = "meinsutoritotekisasu"
          trans = "main street texas"
          chars = "メインストリートテキサス"

        [params.content.audio.tracks.track21]
          tracknum = 21
          name = "kosuto-suramingu"
          trans = "coast slumming"
          chars = "コースト・スラミング"

        [params.content.audio.tracks.track22]
          tracknum = 22
          name = "hoshitachi"
          trans = "the stars"
          chars = "星達"

        [params.content.audio.tracks.track23]
          tracknum = 23
          name = "suketorinku"
          trans = "skating rink"
          chars = "スケートリンク"

        [params.content.audio.tracks.track24]
          tracknum = 24
          name = "yuyo"
          trans = "grace"
          chars = "猶予"

  # Section - Character Bios
  [params.content.characters]
    [params.content.characters.1kady]
      title = 'Kady'
      text = "A young woman who is struggling to find her reason to live. Unemployed, living alone, and without a hobby - she needs to fill that void. And she does when she discovers roller derby. She can be a Debbie Downer at times, but is stronger than she thinks. And she's about to discover just how strong she is!"
      image = 'images/kady.png'

    [params.content.characters.2stella]
      title = 'Stella'
      text = 'A fellow patient from the mental hospital, Stella is smarmy and sassy. But everyone needs a friend who can administer tough love every now and again. Stella convinces Kady to join the local roller derby team and guides her through the trials and tribulations.'
      image = 'images/stella.png'

    [params.content.characters.3hiba]
      title = "Hiba"
      text = "A little hibagon (sasquatch) who assists the player through tutorials and battle mechanics. He's a helpful and kawaii guy."
      image = 'images/hiba.png'

    [params.content.characters.4bcb]
      title = 'Barnes City Brawlers'
      text = 'The local roller derby team, its 7 veteran skaters range from mean girl to gamer geek to exercise freak. Chat with them and buy them gifts to watch your friendship grow!'
      image = 'images/bcb.png'

    [params.content.characters.5glitz]
      title = 'Glitz'
      text = "Head coach of the Brawlers. She is suspicious of the rookie Kady's sudden talent and wonders if she is getting help from somewhere else. But where? Something about the way she skates is familiar..."
      image = 'images/glitz.png'

  # Section - Links
  #
  # Links List #1

  [[params.links]]
    [params.links.list1]
      heading = "Game"

      [[params.links.list1.link]]
        text = "Game OST @ Bandcamp"
        url = "https://nebyoolae.bandcamp.com/album/rorasuketo-ost"

      [[params.links.list1.link]]
        text = "Ghost Sports"
        url = "https://myanimelist.net/manga/29447/Kurogane"

      [[params.links.list1.link]]
        text = "Derby"
        url = "https://en.wikipedia.org/wiki/Roller_derby"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Composer"

      [[params.links.list2.link]]
        text = "MC.Info"
        url = "http://michaelchadwick.info"

      [[params.links.list2.link]]
        text = "Soundcloud"
        url = "https://soundcloud.com/nebyoolae"

      [[params.links.list2.link]]
        text = "Bandcamp"
        url = "http://nebyoolae.bandcamp.com"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Social"

      [[params.links.list3.link]]
        text = "Cam"
        url = "https://www.facebook.com/candice.norcross"

      [[params.links.list3.link]]
        text = "Michael"
        url = "https://www.facebook.com/michael.chadwick"

      [[params.links.list3.link]]
        text = "Tiffany"
        url = "https://www.facebook.com/tiffyjustine"

  # Copyright
  copyright = "&copy;2024 Codana.me"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
