baseURL = "http://rorasuketo.win"
languageCode = "en-us"
title = "Rorasuketo OST"
theme = "hugo-split-theme"

disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "rorasuketo ost"
  description = "ghost sports adventure soundtrack"
  shareImage = "assets/images/social.png"
  twitterHandle = ""

  # Favicon
  favicon = "favicon.png"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/rorasuketo-screen.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      # file = "videos/test.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Section - Content
  [params.content]
    name = "Rorasuketo OST"
    tagline = "Chiptune. Derby."
    bio = "Rorasuketo is a ghost sports adventure created and designed by Candice Norcross, and co-written by Tiffany VanPeenen. Inspired by and orchestrated with classic SNES sounds, the soundtrack was written by Michael Chadwick."

    [params.content.audio]
      enable = true
      autoplay = false
      mute = false
      playlist = true
      #file = "/sounds/main-tema.mp3"
      #soundcloudId = "258744494"
      #bandcampId = "156001537"
      #bandcampUrl = "http://nebyoolae.bandcamp.com/album/rorasuketo-ost"
      #bandcampUrlTitle = "Rorasuketo OST by Nebyoolae"

      [params.content.audio.tracks]
        [params.content.audio.tracks.track01]
          tracknum = 1
          name = "mein-tema"
          trans = "main theme"
          chars = "メインテ ー マ"
          active = true

        [params.content.audio.tracks.track02]
          tracknum = 2
          name = "apato-shizuka"
          trans = "apartment - calm"
          chars = "アパート - 落ち着いた"

        [params.content.audio.tracks.track03]
          name = "apato-isogashi"
          tracknum = 3
          trans = "apartment - busy"
          chars = "アパート - 忙しい"

        [params.content.audio.tracks.track04]
          name = "meinsutoritoamerika"
          tracknum = 4
          trans = "main street usa"
          chars = "メインストリートアメリカ"

        [params.content.audio.tracks.track05]
          name = "roradabi1"
          tracknum = 5
          trans = "roller derby 1"
          chars = "ローラーダービー 1"

        [params.content.audio.tracks.track06]
          name = "lala-tema"
          tracknum = 6
          trans = "lala - theme"
          chars = "ララテ ー マ"

        [params.content.audio.tracks.track07]
          name = "inbo"
          tracknum = 7
          trans = "intrigue"
          chars = "陰謀"

        [params.content.audio.tracks.track08]
          name = "ranburubatoru"
          tracknum = 8
          trans = "rumble battle"
          chars = "ランブルバトル"

        [params.content.audio.tracks.track09]
          name = "shinryosho-sutori"
          tracknum = 9
          trans = "clinic - story/plot"
          chars = "診療所 - ストーリー"

        [params.content.audio.tracks.track10]
          name = "roradabi2"
          tracknum = 10
          trans = "roller derby 2"
          chars = "ローラーダービー 2"

        [params.content.audio.tracks.track11]
          name = "ushinawareta"
          tracknum = 11
          trans = "lost"
          chars = "失われた"

        [params.content.audio.tracks.track12]
          name = "jukuko"
          tracknum = 12
          trans = "ponder"
          chars = "熟考"

        [params.content.audio.tracks.track13]
          name = "utagai"
          tracknum = 13
          trans = "suspicion"
          chars = "疑い"

        [params.content.audio.tracks.track14]
          name = "suketo-shimai"
          tracknum = 14
          trans = "skate sisters"
          chars = "スケート姉妹"

        [params.content.audio.tracks.track15]
          name = "roradabi3"
          tracknum = 15
          trans = "roller derby 3"
          chars = "ローラーダービー 3"

        [params.content.audio.tracks.track16]
          name = "shinryosho-shizuka"
          tracknum = 16
          trans = "clinic - quiet"
          chars = "診療所 - 静か"

        [params.content.audio.tracks.track17]
          name = "roradabi4"
          tracknum = 17
          trans = "roller derby 4"
          chars = "ローラーダービー 4"

        [params.content.audio.tracks.track18]
          name = "yuyo"
          tracknum = 18
          trans = "respite"
          chars = "猶予"

  # Links
  #
  # Links List #1

  [[params.links]]
    [params.links.list1]
      heading = "Game"

      [[params.links.list1.link]]
        text = "Game Home"
        url = "#"

      [[params.links.list1.link]]
        text = "Ghost Sports"
        url = "https://myanimelist.net/manga/29447/Kurogane"

      [[params.links.list1.link]]
        text = "Derby"
        url = "https://en.wikipedia.org/wiki/Roller_derby"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Composer"

      [[params.links.list2.link]]
        text = "MC.Info"
        url = "http://michaelchadwick.info"

      [[params.links.list2.link]]
        text = "Soundcloud"
        url = "https://soundcloud.com/nebyoolae"

      [[params.links.list2.link]]
        text = "Bandcamp"
        url = "http://nebyoolae.bandcamp.com"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Social"

      [[params.links.list3.link]]
        text = "Candice"
        url = "https://www.facebook.com/candice.norcross"

      [[params.links.list3.link]]
        text = "Michael"
        url = "https://www.facebook.com/michael.chadwick"

      [[params.links.list3.link]]
        text = "Tiffany"
        url = "https://www.facebook.com/tiffyjustine"

  # Copyright
  copyright = "&copy;2018 Codana.me"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
