baseURL = "http://rorasuketo.win/"
languageCode = "en-us"
title = "ro-ra-su-ke-to OST"
theme = "hugo-split-theme"

disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "rorasuketo ost"
  description = "ghost sports adventure soundtrack"
  shareImage = "images/social.png"
  twitterHandle = ""

  # Favicon
  favicon = "favicon.png"

  # Copyright
  copyright = "&copy;2018 Codana.me"

  # Section - Content
  [params.content]
    name = "Rorasuketo OST"
    tagline = "Chiptune. Derby."
    bio = "Rorasuketo is a ghost sports adventure created and designed by Candice Norcross, and co-written by Tiffany VanPeenen. Inspired by and orchestrated with classic SNES sounds, the soundtrack was written by Michael Chadwick."

    [params.content.audio]
      enable = true
      autoplay = false
      mute = false
      #file = "/sounds/apato.mp3"
      playlist = true
      #soundcloudId = "258744494"
      #bandcampId = "156001537"
      #bandcampUrl = "http://nebyoolae.bandcamp.com/album/close-to-the-metal"
      #bandcampUrlTitle = "Close to the Metal by Nebyoolae"

      [params.content.audio.tracks]
        [params.content.audio.tracks.track01]
          active = true
          tracknum = 1
          name = "mein-tema"
          trans = "main theme"

        [params.content.audio.tracks.track02]
          name = "apato"
          tracknum = 2
          trans = "apartment"

        [params.content.audio.tracks.track03]
          name = "meinsutoritoamerika"
          tracknum = 3
          trans = "main street usa"

        [params.content.audio.tracks.track04]
          name = "roradabi1"
          tracknum = 4
          trans = "roller derby 1"

        [params.content.audio.tracks.track05]
          name = "lala-tema"
          tracknum = 5
          trans = "lala-theme"

        [params.content.audio.tracks.track06]
          name = "shinryosho-sutori"
          tracknum = 6
          trans = "clinic - story/plot"

        [params.content.audio.tracks.track07]
          name = "roradabi2"
          tracknum = 7
          trans = "roller derby 2"

        [params.content.audio.tracks.track08]
          name = "ushinawareta"
          tracknum = 8
          trans = "lost"

        [params.content.audio.tracks.track09]
          name = "suketo-shimai"
          tracknum = 9
          trans = "skate sisters"

        [params.content.audio.tracks.track10]
          name = "roradabi3"
          tracknum = 10
          trans = "roller derby 3"

        [params.content.audio.tracks.track11]
          name = "shinryosho-shizuka"
          tracknum = 11
          trans = "clinic - quiet"

        [params.content.audio.tracks.track12]
          name = "yuyo"
          tracknum = 12
          trans = "respite/rest"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/rorasuketo-screen.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      # file = "videos/test.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1

  [[params.links]]
    [params.links.list1]
      heading = "Game"

      [[params.links.list1.link]]
        text = "Game Home"
        url = "#"

      [[params.links.list1.link]]
        text = "Ghost Sports"
        url = "https://myanimelist.net/manga/29447/Kurogane"

      [[params.links.list1.link]]
        text = "Derby"
        url = "https://en.wikipedia.org/wiki/Roller_derby"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Composer"

      [[params.links.list2.link]]
        text = "MC.Info"
        url = "http://michaelchadwick.info"

      [[params.links.list2.link]]
        text = "Soundcloud"
        url = "https://soundcloud.com/nebyoolae"

      [[params.links.list2.link]]
        text = "Bandcamp"
        url = "http://nebyoolae.bandcamp.com"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Social"

      [[params.links.list3.link]]
        text = "Candice Norcross"
        url = "https://www.facebook.com/candice.norcross"

      [[params.links.list3.link]]
        text = "Michael Chadwick"
        url = "https://www.facebook.com/michael.chadwick"

      [[params.links.list3.link]]
        text = "Tiffany VanPeenen"
        url = "https://www.facebook.com/tiffyjustine"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
